# Generated by Django 2.1.8 on 2019-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turningaccounts', '0005_turninguser_likeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turninguser',
            old_name='likeUser',
            new_name='userLike',
        ),
    ]
