# Generated by Django 2.1.8 on 2019-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turningaccounts', '0006_turninguser_userfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turninguser',
            name='userGender',
            field=models.CharField(default='', max_length=2),
        ),
    ]
