# Generated by Django 2.1.8 on 2019-08-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turningaccounts', '0007_auto_20190803_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turninguser',
            name='userId',
        ),
        migrations.AlterField(
            model_name='turninguser',
            name='userArmyName',
            field=models.CharField(default='', max_length=5),
        ),
    ]
