# Generated by Django 2.1.8 on 2019-08-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turningaccounts', '0008_auto_20190803_2203'),
        ('turningaccounts', '0007_remove_turninguser_userlike'),
    ]

    operations = [
    ]
