# Generated by Django 2.1.8 on 2019-08-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turningaccounts', '0009_merge_20190808_2128'),
        ('turningaccounts', '0009_merge_20190808_1908'),
    ]

    operations = [
    ]
