# Generated by Django 2.1.8 on 2019-08-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaryBody', models.TextField()),
                ('diaryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoBody', models.TextField()),
                ('checkTodo', models.BooleanField(default=False)),
            ],
        ),
    ]
