# Generated by Django 2.1.8 on 2019-08-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0002_diaryform_tnuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryform',
            name='diaryTitle',
        ),
    ]
