# Generated by Django 2.1.8 on 2019-08-09 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hi', '0002_diaryform_tnuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoTitle', models.CharField(max_length=200)),
                ('todoBody', models.TextField()),
                ('todoStart', models.DateField()),
                ('todoEnd', models.DateField()),
                ('todoCheck', models.BooleanField()),
                ('tnUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
