# Generated by Django 2.1.8 on 2019-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0003_remove_diaryform_diarytitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryform',
            name='diaryDate',
            field=models.DateField(),
        ),
    ]
