# Generated by Django 2.1.8 on 2019-08-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0003_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='tnUser',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='todoCheck',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='todoEnd',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='todoStart',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='todoTitle',
        ),
    ]
