# Generated by Django 2.1.8 on 2019-08-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0004_auto_20190809_2020'),
        ('hi', '0004_auto_20190809_2037'),
    ]

    operations = [
    ]
