# Generated by Django 2.1.8 on 2019-08-09 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Develop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('postHit', models.PositiveIntegerField(default=0)),
                ('tnUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnDevelopUser', to=settings.AUTH_USER_MODEL)),
                ('userLikeName', models.ManyToManyField(related_name='dlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Developcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('develop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Develop')),
                ('tnDevelopCommentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('postHit', models.PositiveIntegerField(default=0)),
                ('tnUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnFreeUser', to=settings.AUTH_USER_MODEL)),
                ('userLikeName', models.ManyToManyField(related_name='flikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Freecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Free')),
                ('tnFreeCommentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('postHit', models.PositiveIntegerField(default=0)),
                ('tnUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turningUser', to=settings.AUTH_USER_MODEL)),
                ('userLikeName', models.ManyToManyField(related_name='nlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Notice')),
                ('noticeCommentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
