# Generated by Django 2.1.8 on 2019-07-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('develop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Develop')),
            ],
        ),
        migrations.CreateModel(
            name='Freecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Free')),
            ],
        ),
        migrations.CreateModel(
            name='Noticecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentdate', models.DateTimeField(auto_now=True, null=True)),
                ('commentbody', models.TextField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Notice')),
            ],
        ),
    ]
