# Generated by Django 2.1.8 on 2019-07-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_noticecomment_noticecommentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='tnUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='자기계발_작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developcomment',
            name='tnDevelopCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='자기계발댓글_작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='free',
            name='tnUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='자유_작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freecomment',
            name='tnFreeCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='자유_댓글작성자', to=settings.AUTH_USER_MODEL),
        ),
    ]
