# Generated by Django 2.1.8 on 2019-07-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190727_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develop',
            name='tnUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnDevelopUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developcomment',
            name='tnDevelopCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnDevelopCommentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='free',
            name='tnUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnFreeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freecomment',
            name='tnFreeCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnFreeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
