# Generated by Django 2.1.8 on 2019-07-27 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_auto_20190727_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='userLikeName',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
