# Generated by Django 2.1.8 on 2019-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190727_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='free',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
