# Generated by Django 2.1.8 on 2019-07-28 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_free_userlikename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='userLikeName',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
