# Generated by Django 2.1.8 on 2019-07-27 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0007_auto_20190727_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
        migrations.AddField(
            model_name='notice',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
