# Generated by Django 2.2.2 on 2019-08-08 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0007_auto_20190728_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='develop',
            name='userLikeName',
            field=models.ManyToManyField(related_name='dlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='free',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='postHit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='userLikeName',
            field=models.ManyToManyField(related_name='nlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developcomment',
            name='tnDevelopCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='free',
            name='userLikeName',
            field=models.ManyToManyField(related_name='flikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freecomment',
            name='tnFreeCommentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
