# Generated by Django 2.1.8 on 2019-07-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190727_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='likes',
        ),
    ]
