# Generated by Django 2.1.8 on 2019-07-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190727_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user',
            new_name='userLike',
        ),
    ]
