# Generated by Django 2.1.8 on 2019-07-27 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_auto_20190727_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='likePoint',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notice',
            name='userLike',
        ),
        migrations.AddField(
            model_name='notice',
            name='userLike',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
