# Generated by Django 2.1.8 on 2019-07-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20190727_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='likePoint',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='userLike',
        ),
    ]
