# Generated by Django 2.1.8 on 2019-07-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20190727_2216'),
        ('board', '0007_auto_20190728_0300'),
    ]

    operations = [
    ]
