# Generated by Django 2.1.8 on 2019-08-03 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0015_auto_20190731_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='userLikeName',
            field=models.ManyToManyField(related_name='dlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='userLikeName',
            field=models.ManyToManyField(related_name='nlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='free',
            name='userLikeName',
            field=models.ManyToManyField(related_name='flikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
