# Generated by Django 2.1.8 on 2019-08-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20190808_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developcomment',
            name='develop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Develop'),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Notice'),
        ),
    ]
