# Generated by Django 2.1.8 on 2019-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20190808_0153'),
        ('board', '0008_auto_20190808_2339'),
    ]

    operations = [
    ]
