# Generated by Django 2.2.4 on 2019-08-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190808_2339'),
        ('board', '0018_auto_20190808_0153'),
    ]

    operations = [
    ]
